# name: deploy order

# on:
#   push:
#     branches:
#       - main

# jobs:
#   # job의 이름 자유롭게 지정, 명세되어 있는게 아님
#   # job name
#   build-and-deploy:
#     # runner
#     runs-on: ubuntu-latest

#     # uses : 약속된 명령어
#     # run : 콘솔 명령
#     steps:
#       - name: checkout github
#         uses: actions/checkout@v2

#       - name: install kubectl
#         uses: azure/setup-kubectl@v3
#         with:
#           version: "v1.35.1"

#       - name: aws configure
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_KEY }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
#           aws-region: us-east-1

#       - name: aws eks cluster update
#         run: aws eks update-kubeconfig --region us-east-1 --name lgcns-kwang-cluster

#       - name: aws ecr login
#         uses: aws-actions/amazon-ecr-login@v1

#       - name: aws ecr - docker image build and push
#         env:
#           # 변수는 기존 명령어와 구분되게 대문자로 작성
#           REGISTRY: 512138915880.dkr.ecr.us-east-1.amazonaws.com
#           REPOSITORY: lgcns-kwang
#           IMAGE_TAG: latest
#         run: |
#           docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f Dockerfile .
#           docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

#       - name: kubectl apply
#         run: |
#           kubectl apply -f k8s/order_redis.yml
#           kubectl apply -f k8s/order_deployment.yml
#           kubectl apply -f k8s/order_ingress.yml
#           kubectl rollout restart deployment order-deployment -n lgcns
